server:
  port: 8080
spring:
  cloud:
    config:
      uri: http://localhost:${config.port:9000}
      name: cloud-config
      profile: dev
  session:
    store-type: hash_map
  application:
    name: cloud-web-ui-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
management:
  security:
    enabled: false





