server:
  port: 9000
spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:davidLv/cloudcms.git
          passphrase: hilary
          search-paths: cloud-config-repo
          clone-on-start: true
          force-pull: true
management:
  security:
    enabled: false

