server:
  port: 8080
  use-forward-headers: true

spring:
  application:
    name: api-gateway
  cloud:
    config:
      uri: http://localhost:${config.port:9000}
      name: cloud-config
      profile: dev
  session:
    store-type: hash_map

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    api-a:
      path: /web/**
      serviceId: web-ui
    auth-api:
      path: /auth-server/**
      serviceId: auth-server
    simple-api:
      path: /simple/**
      serviceId: cloud-simple-service
  add-host-header: true
  ribbon-isolation-strategy: thread
  #add-proxy-headers: true
  #the sensitive-headers usage to control whether to filter the sensitive-headers like cookie, Authortication
  sensitive-headers:
  #ignore-security-headers: false


management:
  security:
    enabled: false

security:
  basic:
    enabled: false
  oauth2:
    client:
      access-token-uri: http://localhost:8080/auth-server/oauth/token
      user-authorization-uri: http://localhost:8080/auth-server/oauth/authorize
      client-id: webapp
    resource:
      user-info-uri: http://localhost:8080/auth-server/user
      prefer-token-info: false
      #id: cloud-simple-service
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000
logging:
  level: debug
#endpoints:
#  cors:
#    allowed-headers: '*'

#adding below to resolve the ZuulException 500 General error
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
